// <auto-generated />
using System;
using DepartmentLoadApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DepartmentLoadApp.Migrations
{
    [DbContext(typeof(DepartmentLoadDbContext))]
    [Migration("20260408092107_FixCoreIntegration")]
    partial class FixCoreIntegration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisciplineBlockBlueAsteriskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisciplineBlockId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DisciplineShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Contingent.ContingentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course1Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course1Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course1Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Subgroups")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBachelor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ContingentRows");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.AcademicPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicCourses")
                        .HasColumnType("integer");

                    b.Property<int>("CoreId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoreId")
                        .IsUnique();

                    b.HasIndex("EducationDirectionId");

                    b.ToTable("AcademicPlansCore");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.AcademicPlanRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicHours")
                        .HasColumnType("integer");

                    b.Property<int>("AcademicPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("CoreId")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseProject")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseWork")
                        .HasColumnType("integer");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int?>("Exam")
                        .HasColumnType("integer");

                    b.Property<int?>("GradedPass")
                        .HasColumnType("integer");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LaboratoryHours")
                        .HasColumnType("integer");

                    b.Property<int?>("Lectures")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Pass")
                        .HasColumnType("integer");

                    b.Property<int?>("PracticalHours")
                        .HasColumnType("integer");

                    b.Property<int?>("Rgr")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("Zet")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPlanId");

                    b.HasIndex("CoreId")
                        .IsUnique();

                    b.HasIndex("DisciplineId");

                    b.ToTable("AcademicPlanRecordsCore");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.EducationDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoreId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoreId")
                        .IsUnique();

                    b.ToTable("EducationDirections");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LecturerDepartmentPostId")
                        .HasColumnType("integer");

                    b.Property<int>("LecturerStudyPostId")
                        .HasColumnType("integer");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoreId")
                        .IsUnique();

                    b.HasIndex("LecturerDepartmentPostId");

                    b.HasIndex("LecturerStudyPostId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.LecturerDepartmentPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoreId")
                        .IsUnique();

                    b.ToTable("LecturerDepartmentPosts");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.LecturerStudyPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer");

                    b.Property<double>("Hours")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoreId")
                        .IsUnique();

                    b.ToTable("LecturerStudyPosts");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoreId")
                        .HasColumnType("integer");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<int?>("CuratorId")
                        .HasColumnType("integer");

                    b.Property<int>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoreId")
                        .IsUnique();

                    b.HasIndex("CuratorId");

                    b.HasIndex("EducationDirectionId");

                    b.ToTable("StudentGroupsCore");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Gia.GiaWorkloadRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GiaSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ManualHours")
                        .HasColumnType("numeric");

                    b.Property<string>("PlanYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GiaWorkloadRows");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<string>("LoadType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LoadCalculations");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<int>("LoadCalculationId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("LoadCalculationId");

                    b.ToTable("LoadDistributions");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.NormTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationBase")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NormTimes");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Practice.PracticeWorkloadRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<string>("PlanYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PracticeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric");

                    b.Property<int>("WeeksCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PracticeWorkloadRows");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.SemesterPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SemesterPeriods");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.StudentFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GroupNames")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GroupsCount")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentFlows");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Workload.WorkloadRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("AcademicPlanRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<decimal>("ConsultationHours")
                        .HasColumnType("numeric");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<decimal>("CourseProjectHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CourseWorkHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CreditHours")
                        .HasColumnType("numeric");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExamHours")
                        .HasColumnType("numeric");

                    b.Property<int>("FlowCount")
                        .HasColumnType("integer");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCourseProject")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCourseWork")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCredit")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExam")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LabPlanHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LabTotalHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LecturePlanHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LectureTotalHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PracticePlanHours")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PracticeTotalHours")
                        .HasColumnType("numeric");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubgroupCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkloadRows");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.AcademicPlan", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.Core.EducationDirection", "EducationDirection")
                        .WithMany()
                        .HasForeignKey("EducationDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EducationDirection");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.AcademicPlanRecord", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.Core.AcademicPlan", "AcademicPlan")
                        .WithMany("Records")
                        .HasForeignKey("AcademicPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentLoadApp.Models.AcademicPlan.Discipline", null)
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("DisciplineId");

                    b.Navigation("AcademicPlan");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.Lecturer", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.Core.LecturerDepartmentPost", "DepartmentPost")
                        .WithMany()
                        .HasForeignKey("LecturerDepartmentPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DepartmentLoadApp.Models.Core.LecturerStudyPost", "StudyPost")
                        .WithMany()
                        .HasForeignKey("LecturerStudyPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartmentPost");

                    b.Navigation("StudyPost");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.StudentGroup", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.Core.Lecturer", "Curator")
                        .WithMany()
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DepartmentLoadApp.Models.Core.EducationDirection", "EducationDirection")
                        .WithMany()
                        .HasForeignKey("EducationDirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curator");

                    b.Navigation("EducationDirection");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadDistribution", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.Core.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentLoadApp.Models.LoadCalculation", "LoadCalculation")
                        .WithMany("LoadDistributions")
                        .HasForeignKey("LoadCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("LoadCalculation");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.Discipline", b =>
                {
                    b.Navigation("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Core.AcademicPlan", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadCalculation", b =>
                {
                    b.Navigation("LoadDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
