// <auto-generated />
using System;
using DepartmentLoadApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DepartmentLoadApp.Migrations
{
    [DbContext(typeof(DepartmentLoadDbContext))]
    [Migration("20260402191128_AddTeachersSemestersFlowsCrud")]
    partial class AddTeachersSemestersFlowsCrud
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.AcademicPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicCourses")
                        .HasColumnType("integer");

                    b.Property<int>("EducationDirectionId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AcademicPlans", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.AcademicPlanRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPlanId")
                        .HasColumnType("integer");

                    b.Property<int?>("AcademicPlanRecordParentId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<bool>("InDepartment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActiveSemester")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsChild")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFacultative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsParent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUseInWorkload")
                        .HasColumnType("boolean");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("Zet")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPlanId");

                    b.HasIndex("AcademicPlanRecordParentId");

                    b.HasIndex("DisciplineId");

                    b.ToTable("AcademicPlanRecords", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.AcademicPlanRecordElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPlanRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("FactHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PlanHours")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AcademicPlanRecordId");

                    b.ToTable("AcademicPlanRecordElements", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisciplineBlockBlueAsteriskName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisciplineBlockId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DisciplineShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Disciplines", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Contingent.ContingentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course1Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course1Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course1Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Subgroups")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsBachelor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ContingentRows", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Gia.GiaWorkloadRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GiaSection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ManualHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PlanYear")
                        .HasColumnType("integer");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("GiaWorkloadRows", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<string>("LoadType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("LoadCalculations", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("LoadCalculationId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoadCalculationId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LoadDistributions", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.NormTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationBase")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("NormTimes", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Practice.PracticeWorkloadRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<int>("PlanYear")
                        .HasColumnType("integer");

                    b.Property<string>("PracticeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("WeeksCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PracticeWorkloadRows", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.SemesterPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SemesterPeriods", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.StudentFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FlowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GroupNames")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GroupsCount")
                        .HasColumnType("integer");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StudentFlows", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExternalLecturerId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Workload.WorkloadRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("AcademicPlanRecordId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ConsultationHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<decimal>("CourseProjectHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CourseWorkHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CreditHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ExamHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("FlowCount")
                        .HasColumnType("integer");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasCourseProject")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCourseWork")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasCredit")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasExam")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LabPlanHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("LabTotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("LecturePlanHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("LectureTotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("PlanYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("PracticePlanHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PracticeTotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubgroupCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkloadRows", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.AcademicPlanRecord", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.AcademicPlan.AcademicPlan", "AcademicPlan")
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("AcademicPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentLoadApp.Models.AcademicPlan.AcademicPlanRecord", "ParentRecord")
                        .WithMany("ChildRecords")
                        .HasForeignKey("AcademicPlanRecordParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DepartmentLoadApp.Models.AcademicPlan.Discipline", "Discipline")
                        .WithMany("AcademicPlanRecords")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicPlan");

                    b.Navigation("Discipline");

                    b.Navigation("ParentRecord");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.AcademicPlanRecordElement", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.AcademicPlan.AcademicPlanRecord", "AcademicPlanRecord")
                        .WithMany("Elements")
                        .HasForeignKey("AcademicPlanRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicPlanRecord");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadDistribution", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.LoadCalculation", "LoadCalculation")
                        .WithMany("LoadDistributions")
                        .HasForeignKey("LoadCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentLoadApp.Models.Teacher", "Teacher")
                        .WithMany("LoadDistributions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoadCalculation");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.AcademicPlan", b =>
                {
                    b.Navigation("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.AcademicPlanRecord", b =>
                {
                    b.Navigation("ChildRecords");

                    b.Navigation("Elements");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.AcademicPlan.Discipline", b =>
                {
                    b.Navigation("AcademicPlanRecords");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadCalculation", b =>
                {
                    b.Navigation("LoadDistributions");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Teacher", b =>
                {
                    b.Navigation("LoadDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
