// <auto-generated />
using DepartmentLoadApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DepartmentLoadApp.Migrations
{
    [DbContext(typeof(DepartmentLoadDbContext))]
    [Migration("20260330161626_AddAcademicPlanTables")]
    partial class AddAcademicPlanTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DepartmentLoadApp.Models.Contingent.ContingentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course1Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course1Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course1Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course2Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course3Subgroups")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Count")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Groups")
                        .HasColumnType("integer");

                    b.Property<int>("Course4Subgroups")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsBachelor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ContingentRows", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadCalculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<string>("LoadType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StudentCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.ToTable("LoadCalculations", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("LoadCalculationId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoadCalculationId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LoadDistributions", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.NormTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationBase")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("NormTimes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationBase = 0,
                            CategoryName = "Аудиторная нагрузка",
                            Hours = 1m,
                            SortOrder = 1,
                            WorkName = "Лекции"
                        },
                        new
                        {
                            Id = 2,
                            CalculationBase = 1,
                            CategoryName = "Аудиторная нагрузка",
                            Hours = 1m,
                            SortOrder = 2,
                            WorkName = "Практические занятия"
                        },
                        new
                        {
                            Id = 3,
                            CalculationBase = 2,
                            CategoryName = "Аудиторная нагрузка",
                            Hours = 1m,
                            SortOrder = 3,
                            WorkName = "Лабораторные работы"
                        },
                        new
                        {
                            Id = 4,
                            CalculationBase = 3,
                            CategoryName = "Контроль",
                            Hours = 0.50m,
                            SortOrder = 4,
                            WorkName = "Экзамены"
                        },
                        new
                        {
                            Id = 5,
                            CalculationBase = 3,
                            CategoryName = "Контроль",
                            Hours = 0.25m,
                            SortOrder = 5,
                            WorkName = "Зачеты"
                        },
                        new
                        {
                            Id = 6,
                            CalculationBase = 4,
                            CategoryName = "Контроль",
                            Hours = 1m,
                            SortOrder = 6,
                            WorkName = "Курсовая работа"
                        },
                        new
                        {
                            Id = 7,
                            CalculationBase = 4,
                            CategoryName = "Контроль",
                            Hours = 1m,
                            SortOrder = 7,
                            WorkName = "Курсовой проект"
                        },
                        new
                        {
                            Id = 8,
                            CalculationBase = 4,
                            CategoryName = "Контроль",
                            Hours = 1m,
                            SortOrder = 8,
                            WorkName = "Рефераты и РГР"
                        },
                        new
                        {
                            Id = 9,
                            CalculationBase = 1,
                            CategoryName = "Контроль",
                            Hours = 1m,
                            SortOrder = 9,
                            WorkName = "Консультации"
                        },
                        new
                        {
                            Id = 10,
                            CalculationBase = 5,
                            CategoryName = "Контроль",
                            Hours = 1m,
                            SortOrder = 10,
                            WorkName = "Консультации перед экзаменом"
                        },
                        new
                        {
                            Id = 11,
                            CalculationBase = 4,
                            CategoryName = "ВКР",
                            Hours = 10m,
                            SortOrder = 11,
                            WorkName = "Руководство ВКР бакалавра"
                        },
                        new
                        {
                            Id = 12,
                            CalculationBase = 4,
                            CategoryName = "ВКР",
                            Hours = 15m,
                            SortOrder = 12,
                            WorkName = "Руководство ВКР магистра"
                        },
                        new
                        {
                            Id = 13,
                            CalculationBase = 4,
                            CategoryName = "ВКР",
                            Hours = 1m,
                            SortOrder = 13,
                            WorkName = "Нормоконтроль ВКР"
                        },
                        new
                        {
                            Id = 14,
                            CalculationBase = 4,
                            CategoryName = "ВКР",
                            Hours = 1m,
                            SortOrder = 14,
                            WorkName = "ГосЭкзамен"
                        },
                        new
                        {
                            Id = 15,
                            CalculationBase = 1,
                            CategoryName = "Практика",
                            Hours = 6m,
                            SortOrder = 15,
                            WorkName = "Учебная практика"
                        },
                        new
                        {
                            Id = 16,
                            CalculationBase = 1,
                            CategoryName = "Практика",
                            Hours = 6m,
                            SortOrder = 16,
                            WorkName = "Производственная практика"
                        },
                        new
                        {
                            Id = 17,
                            CalculationBase = 3,
                            CategoryName = "Практика",
                            Hours = 1m,
                            SortOrder = 17,
                            WorkName = "Преддипломная практика"
                        },
                        new
                        {
                            Id = 18,
                            CalculationBase = 1,
                            CategoryName = "Практика",
                            Hours = 6m,
                            SortOrder = 18,
                            WorkName = "Ознакомительная практика"
                        },
                        new
                        {
                            Id = 19,
                            CalculationBase = 3,
                            CategoryName = "Научная работа",
                            Hours = 1m,
                            SortOrder = 19,
                            WorkName = "НИР"
                        },
                        new
                        {
                            Id = 20,
                            CalculationBase = 3,
                            CategoryName = "Научная работа",
                            Hours = 1m,
                            SortOrder = 20,
                            WorkName = "НИРМ"
                        });
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Workload.WorkloadRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DirectionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FlowCount")
                        .HasColumnType("integer");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("LabPlanHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("LabTotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("LecturePlanHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("LectureTotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PracticePlanHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PracticeTotalHours")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("integer");

                    b.Property<int>("SubgroupCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkloadRows", (string)null);
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadDistribution", b =>
                {
                    b.HasOne("DepartmentLoadApp.Models.LoadCalculation", "LoadCalculation")
                        .WithMany("LoadDistributions")
                        .HasForeignKey("LoadCalculationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepartmentLoadApp.Models.Teacher", "Teacher")
                        .WithMany("LoadDistributions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoadCalculation");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.LoadCalculation", b =>
                {
                    b.Navigation("LoadDistributions");
                });

            modelBuilder.Entity("DepartmentLoadApp.Models.Teacher", b =>
                {
                    b.Navigation("LoadDistributions");
                });
#pragma warning restore 612, 618
        }
    }
}
